<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body>
<div class="wrapper">
    
    <div class="page">
        <div class="main-container col1-layout">
            <div class="main">
            	<div class="col-main">
        			<?php echo $this->getChildHtml('content') ?>
        		</div>
        	</div>
    	</div>    
   </div>
</div>

</body>
</html>